local lush = require "lush"
-- neoclide_coc.nvim:{{{
local neoclide_coc_nvim = lush(function()
    return {
    -- CocHighlightText {},
    -- CocHoverRange {},
    -- CocHintHighlight {},
    -- CocErrorFloat {},
    -- CocWarningFloat {},
    -- CocInfoFloat {},
    -- CocHintFloat {},
    -- CocHintSign {},
    -- CocCodeLens {},
    -- CocErrorSign {},
    -- CocWarningSign {},
    -- CocInfoSign {},
    -- CocHintSign {},
    -- CocErrorHighlight {},
    -- CocWarningHighlight {},
    -- CocInfoHighlight {},
    -- CocWarningVirtualText {},
    -- CocErrorVirtualText {},
    -- CocInfoVirtualText {},
    -- CocHintVirtualText {},
    -- CocGitAddedSign {},
    -- CocGitChangeRemovedSign {},
    -- CocGitChangedSign {},
    -- CocGitRemovedSign {},
    -- CocGitTopRemovedSign {},
    -- CocExplorerBufferRoot {},
    -- CocExplorerBufferExpandIcon {},
    -- CocExplorerBufferBufnr {},
    -- CocExplorerBufferModified {},
    -- CocExplorerBufferBufname {},
    -- CocExplorerBufferFullpath {},
    -- CocExplorerFileRoot {},
    -- CocExplorerFileExpandIcon {},
    -- CocExplorerFileFullpath {},
    -- CocExplorerFileDirectory {},
    -- CocExplorerFileGitStage {},
    -- CocExplorerFileGitUnstage {},
    -- CocExplorerFileSize {},
    -- CocExplorerTimeAccessed {},
    -- CocExplorerTimeCreated {},
    -- CocExplorerTimeModified {},
    -- CocExplorerFileRootName {},
    -- CocExplorerBufferNameVisible {},
  }
end)
return neoclide_coc_nvim
-- }}}
